= Melsicon C++ Sample
:Author:    Oliver Eikemeier
:Email:     <eikemeier@fillmore-labs.com>
:Date:      2021-09
:Revision:  v0.2
:toc: macro

Experiment in setting up a C++ build pipeline.

image:https://badge.buildkite.com/edef4254dcd1c609713e25d8ac67f9c04dba5308f31c408d13.svg?branch=main[title="Buildkite build status",link=https://buildkite.com/melsicon/c-plus-plus-sample]

toc::[]

== Purpose

This code is a simple
https://blog.codinghorror.com/why-cant-programmers-program/[FizzBuzz]
implementation, to play around with a
https://en.wikipedia.org/wiki/C%2B%2B17[C++17] build pipeline.

== Running

=== Prerequisites

You need https://github.com/bazelbuild/bazelisk[Bazelisk] installed, with https://brew.sh[HomeBrew]
just use [source,shell]`brew install bazelbuild/tap/bazelisk`.

=== Tests

To run all tests, use

[source,shell]
bazel test //test/...

=== Main App

Run the app with

[source,shell]
bazel run //main:cpp-sample

or, for the alternate strategy (same result):

[source,shell]
bazel run //main:cpp-sample-alt

=== Dependency Inversion Principle

This code demonstrates the application of the
https://en.wikipedia.org/wiki/Dependency_inversion_principle[dependency inversion principle].
Naively, one would simply make the main programm dependent on the concrete implementation of the
transformation strategy. Here, we simply let the main programm own the interface, making it
independent of the implementation and therefore the strategy exchangable.

[subs="quotes"]
.Dependencies of `//main:main`
----
*bazel query 'filter("^//", kind("source file", deps(//main:main)))'*
_//main:fizzbuzz.h_
_//main:main.cc_
_//main:main.h_
----

Then, to put everything together, link:main/cpp-sample.cc[`cpp-sample.cc`] or
link:main/cpp-sample-alt.cc[`cpp-sample-alt.cc`] pull in the concrete implementaion making a
runnable application:

[subs="quotes"]
.Dependencies of `//main:cpp-sample`
----
*bazel query 'filter("^//", kind("source file", deps(//main:cpp-sample)))'*
_//lib:fizzbuzz.cc_
_//lib:fizzbuzz.h_
_//main:cpp-sample.cc_
_//main:fizzbuzz.h_
_//main:main.cc_
_//main:main.h_
----

[subs="quotes"]
.Dependencies of `//main:cpp-sample-alt`
----
*bazel query 'filter("^//", kind("source file", deps(//main:cpp-sample-alt)))'*
_//lib:fizzbuzz-alt.cc_
_//lib:fizzbuzz-alt.h_
_//main:cpp-sample-alt.cc_
_//main:fizzbuzz.h_
_//main:main.cc_
_//main:main.h_
----

The test depends on both implementations, testing them via the shared interface:

[subs="quotes"]
.Dependencies of `//test:fizzbuzz-test`
----
*bazel query 'filter("^//", kind("source file", deps(//test:fizzbuzz-test)))'*
_//lib:fizzbuzz-alt.cc_
_//lib:fizzbuzz-alt.h_
_//lib:fizzbuzz.cc_
_//lib:fizzbuzz.h_
_//main:fizzbuzz.h_
_//test:fizzbuzz-test.cc_
----


== License

Copyright 2021 melsicon GmbH

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this material except
in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is
distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing permissions and limitations under the
License.
